### ISSUE TITLE
Disable forestry backpacks more

### ISSUE THREAD

**Issue by BBoldt** [asiekierka/MagnumOpus#15]
They are still visible in NEI and so are their recipes.

![](http://i.imgur.com/ITDU6Sy.png)

Since forestry is modular, I would suggest disabling the whole "backpacks and crates" module from forestry.

**Comment by asiekierka** [comment]
@BBoldt - there is no option to disable backpacks (RailCraft DOES have one, which I use), and I don't think I can really complain about crates - don't they work like underpowered BetterStorage Cardboard Boxes?

**Comment by BBoldt** [comment]
There is actually.

/config/forestry/modules.cfg

```
    # Adds backpacks and crates.
    B:storage=true
```

**Comment by BBoldt** [comment]
I only mention crates because they are bundled with backpacks.

**Comment by asiekierka** [comment]
I... I missed that. Okay, let's do that.
