### ISSUE TITLE
Extra Biomes XL strawberries do not work with crop sticks from agricraft

### ISSUE THREAD

**Issue by BBoldt** [asiekierka/MagnumOpus#2]
Proposed solution:

Shapeless recipe from ebxl strawberry seeds to pam's strawberry seeds.

**Comment by BBoldt** [comment]
Or just disable ebxl strawberries completely as they also exist in both plant mega pack and harvestcraft.

These ebxl strawberries are EVERYWHERE.

**Comment by asiekierka** [comment]
I do not think I can disable the strawberries. Hmm.

**Comment by asiekierka** [comment]
But I can disable EBXL's food/crop/seed system, which is HIGHLY redundant.
