### ISSUE TITLE
Request: Allow tools to be repairable without tool station/forge

### ISSUE THREAD

**Issue by BBoldt** [asiekierka/MagnumOpus#3]
I just don't see why I need to take the tool forge with me everywhere just so I can repair a tool on the go. Just seems to be an unnecessary annoyance.

Also, what is the reasoning for not allowing swapping of tool parts? Just curious. It makes for a lot of useless tools as you progress through tiers. Also to delete those tools you need to craft a void chest from railcraft as throwing them in lava or on the ground isn't really an option as they stick around no matter what.

**Comment by BBoldt** [comment]
I just edited this issue into a different one because I didn't realize at the time that the tool forge was actually craftable.

**Comment by asiekierka** [comment]
It is craftable? That is actually a bug of its own.

**Comment by BBoldt** [comment]
I haven't actually tested it but it looks like it is in NEI.

**Comment by asiekierka** [comment]
It is in NEI, as the NEI/creative blocking code is only partially working. I just forgot to edit the MineTweaker scripts.

Anyway, let me edit the issue back, as I solved the repairing...

**Comment by asiekierka** [comment]
Or make a new one.
