### ISSUE TITLE
Certain Forestry features are redundant

### ISSUE THREAD

**Issue by skyem123** [asiekierka/MagnumOpus#32]
The Humus block can be used as farmland. Why can't we add the "crops" item to it?

**Comment by asiekierka** [comment]
Because AgriCraft is the only way of making crops now. I know there are issues with that and Forestry; I plan to disable some of Forestry's features as a result, so I'll keep this open.

**Comment by BBoldt** [comment]
@asiekierka 
You're not planning on disabling the multifarm completely, right?

**Comment by asiekierka** [comment]
@BBoldt - no, because trees.

**Comment by asiekierka** [comment]
Not really redundant.
