### ISSUE TITLE
Right clicking on an immibis microblock makes it disappear

### ISSUE THREAD

**Issue by BBoldt** [asiekierka/MagnumOpus#35]
.... until you relog.

Sometimes also happens when placing an immibis microblock next to another one.

[SMP only, reproduced multiple times on various servers since 1.7.10 - asie]

**Comment by asiekierka** [comment]
It was AE2's fault, fixed, awaiting rv2 beta7

**Comment by asiekierka** [comment]
Fixed in pack19
