### ISSUE TITLE
Railcraft Creosote oil is missing it's texture when in tanks.

### ISSUE THREAD

**Issue by skyem123** [asiekierka/MagnumOpus#37]
In a buildcraft tank it has a pink and black square texture.
In the coke oven internal tank GUI it also has the pink and black square texture.

**Comment by AKTheKnight** [comment]
Pink and Black is the default no texture texture. does this happen for all liquids or just some?

**Comment by skyem123** [comment]
Water has the correct texture in tanks.

**Comment by AKTheKnight** [comment]
hmm, railcraft issue then

**Comment by asiekierka** [comment]
RailCraft has https://github.com/CovertJaguar/Railcraft/issues/383

**Comment by CovertJaguar** [comment]
Its not Railcraft, I was among those who wrote the standards for this. You can be assured I followed them in my own mod.

**Comment by AKTheKnight** [comment]
Looking at the Railcraft #383 seems to be a problem with Artifice, many people have reported it, no sign of change yet

**Comment by AKTheKnight** [comment]
Asie: https://github.com/Shukaro/Artifice/issues/82 Looks like this was fixed in a recent update within the last week

**Comment by asiekierka** [comment]
@AKTheKnight We have removed liquids from Artifice. It's a different mod.

**Comment by Vexatos** [comment]
@asiekierka Get the latest version of [Forestry](http://jenkins.ic2.player.to/job/Forestry_Dev/), that should fix the issue.
