### ISSUE TITLE
Disable update notifications in chat

### ISSUE THREAD

**Issue by Vexatos** [asiekierka/MagnumOpus#38]

**Comment by AKTheKnight** [comment]
That should be easily done in mod configs

**Comment by asiekierka** [comment]
@Vexatos - which mod?

**Comment by Vexatos** [comment]
@asiekierka OpenPrinter still shows the update message, for example; just search the configs for the phrase "update" or "version"

**Comment by asiekierka** [comment]
@Vexatos - I did that on pack1, but I didn't do it after adding more mods. Deferred to alpha release.
