### ISSUE TITLE
Replace HarvestCraft Apiary

### ISSUE THREAD

**Issue by Vexatos** [asiekierka/MagnumOpus#43]
You should remove the HarvestCraft apiary and the beehive world gen. Then you should replace every recipe using bee products with its Forestry equivalents:

| HarvestCraft | Forestry |
| --- | --- |
| Honeycomb | Honey Comb |
| Honey | Honey Drop |
| Beeswax | Beeswax |

Alternatively, you could remove HC Beeswax completely and add a crafting recipe to convert Forestry Beeswax into HC candleberry wax (or completely replace that as well).

The following items/blocks need to be removed from HarvestCraft:
- Apiary (not used anymore)
- Beehive (also the world gen)
- Royal Jelly (not used anymore)
- Waxcomb (not used anymore)
- Bee Queen
- Grub

**Comment by Vexatos** [comment]
I will do the Minetweaker recipes, I'll give you the zs file when I'm done.

**Comment by Vexatos** [comment]
Done. Here is the file: https://gist.github.com/Vexatos/e588fc23cbd5a0e7d30f
Just make sure to disable HarvestCraft Beehive world gen.

**Comment by asiekierka** [comment]
Done.
