### ISSUE TITLE
Right clicking on the Assembly Table crashes the client

### ISSUE THREAD

**Issue by skyem123** [asiekierka/MagnumOpus#46]
Minecraft log: http://paste.ee/p/XZ5Ha
Crash report: http://paste.ee/p/AmerG

**Comment by skyem123** [comment]
I don't know if this is a problem with the Assembly Table or the items in the one I am using.
(The assembly table I'm using is at X:41, Y:74, Z:221)

**Comment by skyem123** [comment]
Testing locally, It seems to be this specific assembly table.

**Comment by asiekierka** [comment]
Fixed for pack18. As a workaround, remove and place the Assembly Table again.

**Comment by skyem123** [comment]
Breaking the assembly table destroyed it.
