### ISSUE TITLE
Can't craft Bibliocraft Clipboard

### ISSUE THREAD

**Issue by BBoldt** [asiekierka/MagnumOpus#47]
It requires an ink sac instead of oredict black dye.

**Comment by Vexatos** [comment]
The Fancy Workbench does as well rewquire an ink sac, it is not dye compatible because it has got that in the recipe specifically due to the ink part.

**Comment by BBoldt** [comment]
Well that's why we have graphite I guess. Pretend you're using a pencil instead of a pen. xD

**Comment by Vexatos** [comment]
Good idea!
