### ISSUE TITLE
Placing a tape drive crashes the server

### ISSUE THREAD

**Issue by skyem123** [asiekierka/MagnumOpus#54]
I placed the tape drive, I was booted off the server.
I logged in again, and the server crashed.

**Comment by skyem123** [comment]
http://i.imgur.com/OAB6inh.jpg

**Comment by skyem123** [comment]
This also happens in singleplayer: http://paste.ee/p/r8nSh

**Comment by skyem123** [comment]
Block updates kick the client from the server.

**Comment by Vexatos** [comment]
@asiekierka Put Computronics on your modpack compiler's blacklist. This is the same issue you had with OpenComputers' OpenOS and other loot floppies.

**Comment by asiekierka** [comment]
Fixed
