### ISSUE TITLE
Block breaker/deployer-style block

### ISSUE THREAD

**Issue by ghost** [asiekierka/MagnumOpus#72]
Is there intentionally no block breaker/deployer-style block, or is it planned for future? I'd love to create some Tekkit/RP-style systems like I used to.

**Comment by Vexatos** [comment]
Can't MCUs do this or are they disabled in the pack?

**Comment by ghost** [comment]
What is an MCU?

**Comment by Vexatos** [comment]
OpenComputers Microcontroller.

**Comment by ghost** [comment]
// Edited

I think only robots can interact with the world.

**Comment by Nentify** [comment]
Nevermind, got it. That's quite neat!

**Comment by asiekierka** [comment]
They're called a _stripes pipe_. Redstone engine to break blocks, no engine to place blocks.

**Comment by ghost** [comment]
Ah, forgot about that one!
